# Eureka Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://66.29.152.193:8090/eureka

spring:
  task:
    scheduling:
      pool:
        size: 5

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

  datasource:
    hikari:
      maximum-pool-size: 50          # 100 connections per microservice
      minimum-idle: 10               # Maintain 10 idle connections
      idle-timeout: 60000            # Close idle connections after 1 minute
      connection-timeout: 30000      # 30-second timeout for obtaining a connection
      max-lifetime: 1800000          # 30-minute max connection lifetime
      pool-name: trringsPool
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://66.29.152.193:5432/trringsdb
    username: trrings
    password: trrings123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: mail.smtp2go.com
    port: 587
    username: pangeanis.com
    password: EG4QKkxv13uItbC9
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    # Set the maximum allowed file size for a single upload
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIARDB3VCI7NAMSIY4I
      secretKey: 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

onesignal:
  appId: dd09e104-a627-47fd-8e42-adb696d8fff1
  apiKey: YmUyNWQwZDItNjNiMS00ODlhLThiMzgtYjkwZDZiZTUyMDUx

application:
  security:
    jwt:
      refresh-token:
        expiration: 31536000000
      expiration: 15552000000
      secret-key: cf56caad05b73d5f76a0cbb87d911f52964307939eedd54ae3e2ec8c5e9d8004
  bucket:
    name: pangeanis-dev
    url: https://pangeanis-dev.s3.ap-south-1.amazonaws.com/


cloudflare:
  r2:
    bucket-name: trrings-dev
    access-key: f2cf8630c470031d625f83625bf9d7cd
    secret-key: 34c3bee7ee108c27721617d2ff30977cfe1640abcc0667ee20244099c57dcc2d
    endpoint-url: https://34000b62cd4a939b78fb911eb8f0f031.r2.cloudflarestorage.com/${cloudflare.r2.bucket-name}/
