server:
  port: 8105
  servlet:
    context-path: /community-service

#GRPC config
grpc:
  server:
    port: 9005
  client:
    user-service:  # name for your auth service client
      address: static://${application.server.host}:9001
      negotiationType: PLAINTEXT  # or TLS if you're using secure communication
      enable-keep-alive: true
      keep-alive-without-calls: true

spring:
  profiles:
    active: dev
  config:
    import:
      #      - optional:classpath:/common.yml
      - common.yml
