# Eureka Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://66.29.152.193:8090/eureka

spring:
  task:
    scheduling:
      pool:
        size: 5

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

  datasource:
    hikari:
      maximum-pool-size: 50          # 100 connections per microservice
      minimum-idle: 10               # Maintain 10 idle connections
      idle-timeout: 60000            # Close idle connections after 1 minute
      connection-timeout: 30000      # 30-second timeout for obtaining a connection
      max-lifetime: 1800000          # 30-minute max connection lifetime
      pool-name: ${DB_POOL}
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: ${MAIL_HOST}
    port: {$MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    # Set the maximum allowed file size for a single upload
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

#AWS properties
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}

onesignal:
  appId: ${ONESIGNAL_APP_ID}
  apiKey: ${ONESIGNAL_API_KEY}

application:
  security:
    jwt:
      refresh-token:
        expiration: ${JWT_REFRESH_EXP}
      expiration: ${JWT_EXP}
      secret-key: ${JWT_SECRET}
  bucket:
    name: ${BUCKET_NAME}
    url: ${BUCKET_URL}
