server:
  port: 8104
  servlet:
    context-path: /moments-service

#GRPC config
grpc:
  server:
    port: 9004
  client:
    authority: localhost:9001

spring:
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:/common.yml
