server:
  port: 8102
  servlet:
    context-path: /post-service

#GRPC config
grpc:
  server:
    port: 9002
  client:
    user-service:  # name for your auth service client
      address: static://${application.server.host}:9001
      negotiationType: PLAINTEXT  # or TLS if you're using secure communication
      enable-keep-alive: true
      keep-alive-without-calls: true

spring:
  profiles:
    active: dev
  config:
    import:
#      - optional:classpath:/common.yml
      - common.yml


application:
  ipUrl: https://ipgeolocation.abstractapi.com/v1/?api_key=91ef750b9c79447fb86dee83b23a5ab7&ip_address=
  postURL: https://pangeanis.com/p/
  commentURL: https://pangeanis.com/c/


#zeggo
zego:
  app-id: 1136374730
  server-secret: 32eab3b9220fa3d339eaf0460e3d0a53
