server:
  port: 8102
  servlet:
    context-path: /space-service

#GRPC config
grpc:
  server:
    port: 9002
  client:
    authority: localhost:9001

spring:
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:/common.yml
