server:
  port: 8101
  servlet:
    context-path: /user-service

#GRPC config
grpc:
  server:
    port: 9001
  client:
    post-service:
      address: static://${application.server.host}:9002
      negotiationType: PLAINTEXT
      enable-keep-alive: true
      keep-alive-without-calls: true


spring:
  profiles:
    active: dev
  config:
    import:
#      - optional:classpath:/common.yml
      - common.yml

twilio:
  accountSid: ACd83092b93878a0835adea44f7d24a0a4
  authToken: 835cc4fc486a447c867ac4399eb94409
  senderPhoneNumber: +12058947136

apple:
  appleAuthEndpoint: https://appleid.apple.com/auth/token
  clientId: com.dev.pangeanis
  clientSecret: eyJraWQiOiJINFJOVlRHSjhSIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiIzRldaNDNIVTVQIiwiaWF0IjoxNzA0OTk5Mjk5LCJleHAiOjE3MjA1NTEyOTksImF1ZCI6Imh0dHBzOi8vYXBwbGVpZC5hcHBsZS5jb20iLCJzdWIiOiJjb20uZGV2LnBhbmdlYW5pcyJ9._RAR8J-BKYLSvIuNEuXol8bsfpdN_8eqczHdhKAwT2xncEs6BwjxAHQUetECO63TKGiev4XIyj_O87pxBanaaA

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.HikariPool: DEBUG
    com.zaxxer.hikari: TRACE
